theme: jekyll-theme-chirpy

lang: en

timezone: Asia/Karachi

title: My University journey

tagline: A student's journey through campus life

description: A personal blog about university life, friendships, studies, and future dreams.

url: "https://raiahmad8882.github.io"

collections:
  tabs:
    output: true
    
github:
  username: raiahmad8882

twitter:
  username:

social:
  name: Rai Ahmad Raza
  email: raiahmad8882@gmail.com
  links:
    - https://github.com/raiahmad8882

theme_mode: dark

avatar: /img/avatar.jpg

toc: true

comments:
  provider:

paginate: 10

sass:
  style: compressed
